### ISSUE TITLE
UnusedIO: init of empty list

### ISSUE THREAD

**Issue by NeQuissimus** [typelevel/typelevel-scalafix#19]
I am writing tests using `munit.CatsEffectSuite` and using `typelevel-scalafix v0.1.3`.

```scala
import munit.CatsEffectSuite

final class MySuite extends CatsEffectSuite {
  test("foo") {}
}
```

This will result in

```
[error] Caused by: java.lang.UnsupportedOperationException: init of empty list
[error] 	at scala.collection.immutable.Nil$.init(List.scala:666)
[error] 	at scala.collection.immutable.Nil$.init(List.scala:661)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$checkTree$1.applyOrElse(UnusedIO.scala:90)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$checkTree$1.applyOrElse(UnusedIO.scala:84)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
```

**Comment by DavidGregory084** [comment]
Oh dear, this is a very daft bug 😆 of course a Term.Block can have no statements in it.

**Comment by DavidGregory084** [comment]
Thanks for the report @NeQuissimus - will release a fix for this sometime this afternoon :D
