### ISSUE TITLE
UnusedIO - MatchError: throw (e)

### ISSUE THREAD

**Issue by NeQuissimus** [typelevel/typelevel-scalafix#34]
This is an interesting one :)

I (accidentally) ran `UnusedIO` against a code base that does not use IO at all.

I cannot share the code but it would appear that `throw e` can cause issues.

```
[error] Caused by: scala.MatchError: throw (e) (of class scala.meta.Term$Throw$TermThrowImpl)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$self$lzycompute$1$1.$anonfun$applyOrElse$2(UnusedIO.scala:68)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$self$lzycompute$1$1.applyOrElse(UnusedIO.scala:68)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$self$lzycompute$1$1.applyOrElse(UnusedIO.scala:49)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
[error] 	at org.typelevel.fix.UnusedIO.org$typelevel$fix$UnusedIO$$checkInner$1(UnusedIO.scala:76)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$self$lzycompute$1$1.$anonfun$applyOrElse$1(UnusedIO.scala:65)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$self$lzycompute$1$1.applyOrElse(UnusedIO.scala:63)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$self$lzycompute$1$1.applyOrElse(UnusedIO.scala:49)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
[error] 	at org.typelevel.fix.UnusedIO.org$typelevel$fix$UnusedIO$$checkInner$1(UnusedIO.scala:76)
[error] 	at org.typelevel.fix.UnusedIO.checkDiscardedStat(UnusedIO.scala:79)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$checkTree$1.$anonfun$applyOrElse$3(UnusedIO.scala:90)
[error] 	at scala.collection.immutable.List.map(List.scala:250)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$checkTree$1.applyOrElse(UnusedIO.scala:90)
[error] 	at org.typelevel.fix.UnusedIO$$anonfun$checkTree$1.applyOrElse(UnusedIO.scala:84)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
[error] 	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$3$.apply(Api.scala:32)
```

**Comment by custommonkey** [comment]
I've hit the same error but for `Term.Assign`.

ATM the implementation is using `map` with a partial function to test if the recursive call to `checkInner` if able to match the next node. 

```
stats.map {
    case stat if self.isDefinedAt(stat) =>
        checkInner(stat)
}.asPatch
```

If `checkInner` doesn't have a case for that node type it will fail. Simple fix would be to change `map` to `collect`, but I'm not sure that what we want as it would stop processing that branch.

Another option is to add the missing cases into `checkInner`

**Comment by DavidGregory084** [comment]
I'm trying to get my head back into this one to understand what we need to do...

So the way this lint is currently structured, we look for opportunities for IOs to be discarded in `checkTree`. That means we look for things like imperative control structures (`for`, `while`, `try`), class bodies, constructors and most importantly blocks.

A block can contain multiple statements and it's *only* the final statement that is safe from being discarded.

Note that we *don't* look for `val` or `def` or other `Decl`s and `Defn`s because they can be referred to in the final expression. We don't currently attempt to do any control flow analysis or anything like that to determine whether any IOs in `val`s or `def`s are discarded.

I believe that the ZIO equivalent of this plugin does do that, but it seems overkill to me because those can be picked up by other lints (`-Wunused`).

Once we have identified an *opportunity* for a value to be discarded, we try to figure out what the type of the expression being discarded is in `checkDiscardedStat` by applying `checkSignature` to the consituents of the expression that is discarded.

We know that we don't care about the other subtypes of `Stat` (`Decl`, `Defn`) so we can focus on `Term`. Unfortunately this is still a huge data type as the Scala AST is very complicated.

So it looks like at the very least we should add cases to check the body and catch expressions of `Try` and `TryWithHandler`, the ascribed expression of `Ascribe`, the annottee of `Annotate` and the args of `Tuple`, the `op` of `ApplyUnary`, and perhaps the `fun` of `ApplyUsing` which I guess is a Scala 3.x thing?

It also makes sense to me to use `collect` as @custommonkey suggests to ignore the cases that we don't understand or don't care about (such as `Assign` and `Throw`), on the basis that it's better to miss a warning than to break someone's build spuriously.

**Comment by DavidGregory084** [comment]
Took a crack at this on @custommonkey's PR #42

**Comment by DavidGregory084** [comment]
Should be fixed in 0.1.5 @NeQuissimus, let us know how it goes! 😁
